---
- name: Installer et configurer Kubernetes
  hosts: master
  become: yes
  tasks:

    - name: Désactiver le swap
      command: swapoff -a

    - name: Commenter le swap dans fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)$'
        replace: '#\1'

    - name: Charger les modules nécessaires
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Appliquer les modules
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Configurer les paramètres sysctl pour Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Appliquer la configuration sysctl
      command: sysctl --system

    - name: Ajouter le repo Kubernetes
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Installer kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet=1.29.3-1.1
          - kubeadm=1.29.3-1.1
          - kubectl=1.29.3-1.1
        state: present
        update_cache: yes

    - name: Activer le service kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
